name: storekeeper_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  path: ^1.9.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
